apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: multigres-operator
    app.kubernetes.io/component: gc
    app.kubernetes.io/managed-by: kustomize
  name: gc
  namespace: system
